### ISSUE TITLE
[Barcelona] bootstrap.properties uses edgex hostname for host

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/support-scheduler#23]
I did some work to ensure that all my services are registering to Consul when run from within my edgexfoundry-core snap [1], and I noticed that after I enabled Consul for support-scheduler, that it crashed as it wasn't able to resolve the hostname _edgex-core-consul_. It turns out all of the other core-* and support-* services specify that **spring.cloud.consul.host=localhost** except for support-scheduler. 

My snap is building from the barcelona branch of support-scheduler.  I'm currently working around the problem in my start-edgex script [2], so this a low-priority item, and would only impact someone if they enabled consul in the service's local bootstrap.properties file.

[1] https://github.com/tonyespy/edgex-core-snap

[2] https://github.com/tonyespy/edgex-core-snap/blob/master/bin/start-edgex.sh

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
