### ISSUE TITLE
Reset scheduling exists in bug

### ISSUE THREAD

**Issue by 935560217** [edgexfoundry/support-scheduler#28]
There is a problem in method parsePeriodAndDuration (String frequency) in file ScheduleContext.java.
The first if goes missing {}.

   private void parsePeriodAndDuration(String frequency) {

    int periodStart = frequency.indexOf('P');
    int timeStart = frequency.indexOf('T');
    String freq = frequency;

    this.period = Period.ZERO;
    this.duration = Duration.ZERO;

    // Parse out the period (date)
    try {
      // If there is a duration 'T', remove it
      if (timeStart != -1)
        freq = frequency.substring(periodStart, timeStart);
        this.period = Period.parse(freq);

    } catch (IndexOutOfBoundsException | DateTimeParseException e) {
      logger.error("parsePeriodAndDuration() failed to parse period from '" + freq + "'");
    }

    // Parse out the duration (time)
    try {
      // Make sure there is both a 'P' and 'T'
      if (periodStart != -1 && timeStart != -1) {
        freq = frequency.substring(timeStart, frequency.length());
        this.duration = Duration.parse("P" + freq);
      }
    } catch (IndexOutOfBoundsException | DateTimeParseException e) {
      logger.error("parsePeriodAndDuration() failed to parse duration from 'P" + freq + "'");
    }
  }

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
